spring:
  datasource:
    url: ${DATASOURCE_JDBC_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  http:
    clients:
      imperative:
        factory: http_components
    serviceclient:
      fastpay:
        base-url: ${algashop.integrations.payment.fastpay.host}
        default-header:
          Token: ${algashop.integrations.payment.fastpay.private-token}

algashop:
  integrations:
    payment:
      provider: FASTPAY
      fastpay:
        host: ${FASTPAY_HOST}
        private-token: ${FASTPAY_PRIVATE_TOKEN}
        webhook-url: ${FASTPAY_WEBHOOK_URL}